# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from . import example_pb2 as example__pb2
#import example_pb2 as example__pb2


class multiplicarStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.multiplicar = channel.unary_unary(
                '/multiplicar/multiplicar',
                request_serializer=example__pb2.multiplicarRequest.SerializeToString,
                response_deserializer=example__pb2.multiplicarReply.FromString,
                )
        self.dividir = channel.unary_unary(
                '/multiplicar/dividir',
                request_serializer=example__pb2.multiplicarRequest.SerializeToString,
                response_deserializer=example__pb2.multiplicarReply.FromString,
                )
        self.mega = channel.unary_unary(
                '/multiplicar/mega',
                request_serializer=example__pb2.megaRequest.SerializeToString,
                response_deserializer=example__pb2.megaReply.FromString,
                )


class multiplicarServicer(object):
    """Missing associated documentation comment in .proto file."""

    def multiplicar(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def dividir(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def mega(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_multiplicarServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'multiplicar': grpc.unary_unary_rpc_method_handler(
                    servicer.multiplicar,
                    request_deserializer=example__pb2.multiplicarRequest.FromString,
                    response_serializer=example__pb2.multiplicarReply.SerializeToString,
            ),
            'dividir': grpc.unary_unary_rpc_method_handler(
                    servicer.dividir,
                    request_deserializer=example__pb2.multiplicarRequest.FromString,
                    response_serializer=example__pb2.multiplicarReply.SerializeToString,
            ),
            'mega': grpc.unary_unary_rpc_method_handler(
                    servicer.mega,
                    request_deserializer=example__pb2.megaRequest.FromString,
                    response_serializer=example__pb2.megaReply.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'multiplicar', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class multiplicar(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def multiplicar(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/multiplicar/multiplicar',
            example__pb2.multiplicarRequest.SerializeToString,
            example__pb2.multiplicarReply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def dividir(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/multiplicar/dividir',
            example__pb2.multiplicarRequest.SerializeToString,
            example__pb2.multiplicarReply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def mega(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/multiplicar/mega',
            example__pb2.megaRequest.SerializeToString,
            example__pb2.megaReply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
